apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: hello-github-listener-interceptor
  name: hello-github-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: hello-github-listener