apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: hello-el
  name: el-hello
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-hello-el