
   
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: hello-el
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-listener
    bindings:
      - ref: hello-pipeline-binding
    template:
      ref: hello-trigger-pipeline-template