apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-hello-world
  namespace: tekton-buildah-hello-demo
spec:
  pipelineRef:
    name: pipeline-hello-world
  params:
  - name: APP_NAME
    value: springboot-hello-world
  - name: GIT_URL
    value: https://github.com/malam84/springboot-hello-world.git
  - name: GIT_REVISION
    value: master
  - name: manifest-dir
    value: template
  - name: image-name
    value: image-registry.openshift-image-registry.svc:5000/tekton-buildah-hello-demo/springboot-hello-world:latest
  workspaces:
  - name: maven-source
    persistentVolumeClaim:
      claimName: maven-source-pvc
  - name: maven-cache-repo
    persistentVolumeClaim:
      claimName: maven-cache-repo-pvc
  - name: maven-settings
    configMap:
      name: maven-settings