apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-hello-world
  namespace: tekton-buildah-hello-demo
spec:
  params:
    - default: springboot-hello-world
      description: The application deployment name
      name: APP_NAME
      type: string
    - default: 'https://github.com/malam84/springboot-hello-world.git'
      description: The application git repository url
      name: GIT_URL
      type: string
    - default: master
      description: The application git repository revision
      name: GIT_REVISION
      type: string
    - name: image-name
      type: string
      description: The image full path to host the built image, with version tag, e.g. image-registry.openshift-image-registry.svc:5000/
      default: image-registry.openshift-image-registry.svc:5000/tekton-buildah-hello-demo/springboot-hello-world:latest
    - name: manifest-dir
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: maven-source
    - name: mvn-test
      params:
        - name: GOALS
          value:
            - verify
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-cache-repo
          workspace: maven-cache-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: maven-source
    - name: mvn-package
      params:
        - name: GOALS
          value:
            - package
            - '-DskipTests'
      runAfter:
        - mvn-test
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-cache-repo
          workspace: maven-cache-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: maven-source
    - name: build-image
      params:
      - name: IMAGE
        value: '$(params.image-name)'
      - name: TLSVERIFY
        value: "false"
      runAfter:
        - mvn-package
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: maven-source
    - name: deploy
      taskRef:
        name: redeploy
        kind: Task
      runAfter:
      - build-image
      params:
      - name: DEPLOYMENT_NAME
        value: $(params.APP_NAME)
      - name: DEPLOYMENT_IMAGE_NAME
        value: $(params.image-name)
      workspaces:
      - name: source
        workspace: maven-source
  workspaces:
    - name: maven-source
    - name: maven-settings
    - name: maven-cache-repo




#################################################################






