apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source-pvc
  namespace:  hello-tekton-buildah-demo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv0001
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-repo-pvc
  namespace: hello-tekton-buildah-demo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv0002
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
