---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-task-cache-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv0005
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv0006
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle 
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-repo-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pv0007
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 


